### ISSUE TITLE
config file for os environment variable definitions

### ISSUE THREAD

**Issue by nikparth** [brain-score/brain-score#190]
It would be nice to have a config file that had the default environment variables used throughout the code to define paths that are used for downloading the datasets that are used (i.e. neural/image data, imagenet data for LayerPCA etc.). I have a separate scratch machine on a cluster for large data and can't fill the default home directories with this data and I couldn't find how to set this without digging into the code. Specifically, I think the ones I needed to set are "BRAINIO_HOME" (in [fetch.py](https://github.com/brain-score/brainio_collection/blob/master/brainio_collection/fetch.py)  and "'MT_IMAGENET_PATH" in [pca.py]( https://github.com/brain-score/model-tools/blob/master/model_tools/activations/pca.py)), but it would nice to have a main config file somewhere with comments listing these and putting the default values there. If there is already something like this sorry, but if you could point to that file that would be great. I'm happy to contribute something for this looking through at any other relevant os environment variables if others think it is valuable.

**Comment by mschrimpf** [comment]
We tried to list the environment variables per repository which unfortunately makes the info a little scattered. 
Due to the way the code is structured right now, we would probably need one of these config files per repository, is that what you were thinking of?

Here's the full current list:

from [result-caching](https://github.com/brain-score/result_caching#environment-variables)
- `RESULTCACHING_HOME`
- `RESULTCACHING_DISABLE`
- `RESULTCACHING_CACHEDONLY`

from [brainio_collection](https://github.com/brain-score/brainio_collection)
- `BRAINIO_HOME`

from [model-tools](https://github.com/brain-score/model-tools#environment-variables)
- `MT_MULTITHREAD`
- `MT_HOME`
- `MT_IMAGENET_PATH`

from [candidate_models](https://github.com/brain-score/candidate_models#environment-variables)
- `CM_HOME`
- `CM_TSLIM_WEIGHTS_DIR`

**Comment by nikparth** [comment]
Yeah I was thinking something like one file for each repo that just lists them with a default value and those files get sourced or imported in the other files that use them so that we don't have to go set those in the actual code to make changes.

**Comment by mschrimpf** [comment]
My worry is that while defining those files would initially be really helpful, in the long run maintaining them will be difficult. E.g. people will forget to add new environment variables to those files.
Do you know how other frameworks (e.g. pytorch) handle this?

**Comment by nikparth** [comment]
Yeah I see what you're saying- I'm doing some digging- i'll propose something when I have a cleaner solution.

**Comment by mschrimpf** [comment]
closing this for now, please feel free to re-open!
