### ISSUE TITLE
Score individual blocks?

### ISSUE THREAD

**Issue by aaprasad** [brain-score/brain-score#312]
I have a couple questions about brainscore

1. Is there a way to score each individual block of a network, for example, VGG 16
2. Can we score pretrained models (IE if i want to train a model on a different dataset and then compute its brainscore how would I do this)
3. Can I score new images - do I need to have the corresponding neural stimulus

**Comment by mschrimpf** [comment]
Hi aaprasad,

1. yes but it would have to be in separate submissions -- you can specify separate blocks per submission in the [`get_layers` method](https://github.com/brain-score/sample-model-submission/blob/master/models/base_models.py#L30-L40)
2. yes, all models on the website right now are pre-trained. Typically they load their weights upon creating the model, e.g. from [S3](https://github.com/dicarlolab/CORnet/blob/master/cornet/__init__.py#L19-L22) or from [another host](https://github.com/brain-score/candidate_models/blob/cd3bd3dc755fd318c3b5885d082e803b6e104d9c/candidate_models/base_models/__init__.py#L289-L294). We have also scored pre-trained e.g. [torchvision models](https://github.com/brain-score/candidate_models/blob/cd3bd3dc755fd318c3b5885d082e803b6e104d9c/candidate_models/base_models/__init__.py#L18-L25)
3. upon submission, you do not need all stimuli that your model will be tested on. You submit a model and the submission system will internally ask the model to generate predictions for new images. Check out the [model tutorial](https://brain-score.readthedocs.io/en/latest/modules/model_tutorial.html) and the [sample-model-submission](https://github.com/brain-score/sample-model-submission) for more details

Hope this helps!

**Comment by aaprasad** [comment]
Hi Martin, thanks for the fast responses!

One last question, I was wondering if you could clarify the difference between these two lines

1. `vgg16_wrapper = PytorchWrapper(identifier='vgg16', model=vgg16(pretrained=True), preprocessing=preprocessing)`
2. `vgg16_activations = vgg16_wrapper(stimuli=[stimuli_path], layers=['features'])`

My understanding is that both `vgg16_wrapper` and `vgg16_activations` are the activations of the `vgg16` model but when I try passing `vgg_activations` into `vgg16_model = ModelCommitment(identifier='vgg16', activations_model=vgg16_activations, layers=['features'])` and then try scoring it as  `score = score_model(model_identifier="vgg16", model=vgg16_model, benchmark_identifier='dicarlo.MajajHong2015public.IT-pls')`, I get an attribute error for `NeuroidAssembly` while when I use `vgg_wrapper` I dont get this error. Is the only difference that `vgg_activations` allows me to actually view the activations?

**Comment by mschrimpf** [comment]
The `vgg16_wrapper` helps to _retrieve_ activations. Basically it's a wrapper around a model that you can feed with stimuli and a list of layers, and it returns the activations for those layers.
This is exactly what you do in 2: you retrieve activations from the wrapper.

The `ModelCommitment` class expects an `activations_model` which it uses to retrieve activations from the model. Passing in the activations directly doesn't work for that.

In general, models submitted to brain-score are expected to produce features in response to new images, you do _not_ submit the features themselves. This is so that models can be tested on future benchmarks and to prevent overfitting.

Does that make sense?
