### ISSUE TITLE
Can we see pending submissions?

### ISSUE THREAD

**Issue by heydarshahi** [brain-score/brain-score#321]
Hi all!
 
Is there a list of pending submissions after users submit their models before the evaluation is complete? 

Thanks,
Amin

**Comment by mschrimpf** [comment]
Hi Amin,

At the moment unfortunately not in a straight-forward way -- but you can look for your submission here: http://braintree.mit.edu:8080/job/run_benchmarks/.
We are planning to implement this in the profile so that you can easily see all your submissions, pending as well as completed, but it will take us some time to get to this feature.

Best,
Martin

**Comment by heydarshahi** [comment]
That's great. Thanks!
