### ISSUE TITLE
Different benchmark results in the board vs. detailed view

### ISSUE THREAD

**Issue by heydarshahi** [brain-score/brain-score#325]
Hi all,

When I look at my submissions in the profile, I get an average score of 0.352 as in the image:
![image](https://user-images.githubusercontent.com/79289947/168638851-9992603b-288d-49b2-93b4-dca67e6a0b74.png)

But when I click on the model to see the details, I get different values:

![image](https://user-images.githubusercontent.com/79289947/168639176-8f2687a2-cbaa-47fb-bb07-b022d66c1742.png)

Any ideas why this is happening and which score I should trust?

Many thanks,

Amin

**Comment by mschrimpf** [comment]
Hi @heydarshahi, 

The table in your profile also shows scores on benchmarks that are not (yet) public, for instance `MajajHong2015.IT-rdm` in `IT`.

The model view only shows scores on benchmarks that are public, notice there are only 5 benchmarks in IT rather than 7 in your profile.

Sorry for this confusion, it's on our list of things to fix and make more intuitive.

**Comment by heydarshahi** [comment]
I see. Thanks for the clarification :)
