### ISSUE TITLE
The webpage seems to be down

### ISSUE THREAD

**Issue by lee-wanhee** [brain-score/brain-score#411]
Hi, I am a participant in the brain-score model submission. First of all, thank you so much for your amazing work. 

I have tried to log in to the brain-score website (brain-score.org), but it has not worked for me for the past few days. Could you check whether the problem is on my side?

**Comment by mike-ferguson** [comment]
Hi Wanhee, thanks for opening an issue. What errors are you encountering? If you are unable to login because you get a `403` error, please note we have had issues recently regarding `https` and `http` - I would suggest trying to login using `http://www.brain-score.org/profile`. If the issue still persists even when not using `https`, please let us know! Thanks

**Comment by lee-wanhee** [comment]
Thank you so much for checking! I could login using HTTP.
